# https://github.com/nginxinc/kubernetes-ingress/tree/v2.1.1/deployments/helm-chart
controller:
  ingressClass: "http-default"
  enableTLSPassthrough: false
  healthStatus: true
  replicaCount: 2
  service:
    httpPort:
      enable: false
    httpsPort:
      enable: true
      targetPort: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: " arn:aws:acm:us-east-1:785632507427:certificate/fe70ca7a-7526-42a6-b431-d5d1f95483a2"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  config:
    name: http-controller-nginx-ingress
    entries:
      worker-connections: "2048"
